### ISSUE TITLE
Follow C# naming conventions

### ISSUE THREAD

**Issue by YuvalItzchakov** [aerospike/aerospike-client-csharp#10]
Throughout the code, there is no sticking to C# coding covnentions.
For example, in the record class:

    public readonly Dictionary<string,object> bins;
    public readonly int generation;
    public readonly int expiration;

You expose public fields, instead of properties, and the naming convention is CamelCase, where you use pascalCase.
Are you guys accepting pull requests?

**Comment by Caldas** [comment]
Agree, @YuvalItzchakov I beleive it would be nice to have a PR with it.
