### ISSUE TITLE
Listing namespaces / sets

### ISSUE THREAD

**Issue by Caldas** [aerospike/aerospike-client-csharp#11]
How can I list namespaces and sets inside namespaces using C# client?

**Comment by manigandham** [comment]
Do a 'Info' request. Aerospike has a info service that returns a name/value string of config and status information.

For example to get information about namespaces, get the list of nodes and use a node to send a request for info and select the term that you're interested in.

    var nodes = aerospikeClient.Nodes;
    var namespacesRaw = Info.Request(nodes[0].GetConnection(1000), "namespaces");
    var namespaces = namespacesRaw.Split(';').ToList();

**Comment by Caldas** [comment]
@manigandham list namespace Ok ...

Do you know how to list set into a specific namespace?

**Comment by manigandham** [comment]
https://docs.aerospike.com/display/V3/asinfo+-+Read+Parameters

filter by "namespaces/namespaceYouWant"

**Comment by Caldas** [comment]
It was possible to know more about sets using

```
var nodes = aerospikeClient.Nodes;
var namespacesRaw = Info.Request(nodes[0].GetConnection(1000), "sets");
var namespaces = namespacesRaw.Split(';').ToList();
```

**Comment by Caldas** [comment]
Others possibles commands are avaliable at http://www.aerospike.com/docs/reference/info/

**Comment by Caldas** [comment]
Thanks a lot @manigandham :+1:
