### ISSUE TITLE
Switch to license expression

### ISSUE THREAD

**Issue by thompson-tomo** [aerospike/aerospike-client-csharp#115]
### Summary
I wish for the nuget packages to have the licence expression property set correctly.

### Details

The licence expression property should be set to the correct licence type I.e. Apache-2.0 as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by shannonklaus** [comment]
Closing this issue as this suggestion was implemented in release 7.2.0.
