### ISSUE TITLE
System.IndexOutOfRangeException When Unpacking Map

### ISSUE THREAD

**Issue by Smoles** [aerospike/aerospike-client-csharp#19]
When trying to use the latest Aerospike C# driver (3.2.4) calling AerospikeClient.Get() on certain existing records throw the following exception. 

The version of Aerospike we are using is 3.9.1, though we had seen this same problem when we were on the 3.7.x version. We upgraded Aeropsike thinking maybe there was a compatibility issue between the server and driver versions but that doesn't seem to be the case.

System.IndexOutOfRangeException: Index was outside the bounds of the array. at Aerospike.Client.Unpacker.CreateMap(Int32 count) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Util\Unpacker.cs:line 178 at Aerospike.Client.Unpacker.UnpackMap(Int32 count) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Util\Unpacker.cs:line 129 at Aerospike.Client.ByteUtil.BytesToParticle(Int32 type, Byte[] buf, Int32 offset, Int32 len) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Command\ByteUtil.cs:line 83 at Aerospike.Client.ReadCommand.ParseRecord(Int32 opCount, Int32 fieldCount, Int32 generation, Int32 expiration) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Command\ReadCommand.cs:line 161 at Aerospike.Client.ReadCommand.ParseResult(Connection conn) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Command\ReadCommand.cs:line 98 at Aerospike.Client.SyncCommand.Execute() in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Command\SyncCommand.cs:line 102 at Aerospike.Client.AerospikeClient.Get(Policy policy, Key key) in d:\SourceCode\Aerospike\aerospike-client-csharp-3.2.4\AerospikeClient\Main\AerospikeClient.cs:line 438 ...

**Comment by BrianNichols** [comment]
This is a bug.  We will fix in the next release.  You can manually patch the source code by changing Unpacker.cs line 126 to:
```
	return new Dictionary<object, object>(0);
```

**Comment by Smoles** [comment]
That fixed the issue. Thanks!

**Comment by BrianNichols** [comment]
C# client has been released:

http://www.aerospike.com/download/client/csharp/3.3.0
