### ISSUE TITLE
How to use Predicate Filtering

### ISSUE THREAD

**Issue by Caldas** [aerospike/aerospike-client-csharp#23]
How can I use [Predicate Filtering](http://www.aerospike.com/docs/guide/predicate.html) from C# client?

**Comment by BrianNichols** [comment]
Look at QueryPredExp.cs in the AerospikeDemo project.

https://github.com/aerospike/aerospike-client-csharp/blob/master/Framework/AerospikeDemo/QueryPredExp.cs

**Comment by Caldas** [comment]
Thanks,

Another question. Why on the sample there is a lua filter registration If
se dont see an aggregation call? When the UDF is used on this case?

Em 30 de mar de 2017 2:45 PM, "Brian Nichols" <notifications@github.com>
escreveu:

**Comment by BrianNichols** [comment]
It's not needed.  The example was apparently copied from an other example and then modified for PredExp and wasn't completely cleaned up.  We will remove Register() from the PredExp example in the next release.

**Comment by Caldas** [comment]
Thanks, since it's not needed I will be able to upgrade my project to .net core ;)
