### ISSUE TITLE
.NET Standard and Nuget packaging

### ISSUE THREAD

**Issue by bmdub** [aerospike/aerospike-client-csharp#27]
The Aerospike client as downloaded from Nuget causes dll conflict warnings when used from within a .NET Standard project:

_warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved._

The problem can be resolved by changing the project to target .NET Standard 1.6 from 1.4, so that Aerospike and the library are both referencing the same version of the common libraries.

Retargeting would normally not be an issue; however, .NET Standard 1.6 libraries cannot currently be referenced by .NET Framework projects (at least, until later this year according to Microsoft), forcing us to target 1.4.

So I suppose my question is:  Does the Aerospike client need to target .NET Standard 1.6, or will it work fine targeting 1.4?  Microsoft recommends targeting the lowest version possible (https://docs.microsoft.com/en-us/dotnet/standard/library).
Otherwise it might be ok to eat this warning until later this year.

**Comment by BrianNichols** [comment]
If project.json is changed to reference NETStandard 1.4, several warnings and an error about BufferedStream not being available is generated.

**Comment by bmdub** [comment]
No warnings or erros when targeting NETStandard 1.5.  NETStandard 1.5 would also solve this problem for us.

Also, the nuget package doesn't seem to define the minimal NETStandard requirement, allowing users targeting 1.4 to mistakenly be able to reference this package.

**Comment by BrianNichols** [comment]
I get one warning (which may be benign) when specifying NETStandard 1.5 in project.json:

_project.json(9,34): warning NU1007: Dependency specified was NETStandard.Library >= 1.5.0 but ended up with NETStandard.Library 1.6.0._

Can you issue a pull request for "project.json", "AerospikeClient.nuspec" and other necessary files to obtain compatibility and define minimal NETStandard requirement?  I want to make sure we are on the same page before releasing the client.

**Comment by BrianNichols** [comment]
Thanks for the pull request.  We will integrate these changes into the next C# client release.

**Comment by BrianNichols** [comment]
C# client released today.

http://www.aerospike.com/download/client/csharp/3.4.4/
