### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by kuskmen** [aerospike/aerospike-client-csharp#33]
Hi, 

we are using this client in our company code base and I was just searching for some open source project to join into so I was wondering if you are interested in any kind of performance tweaks I can make and not only that but join the project with whatever I can do. Is there some sort of documentation/code of conduct?

Regards,
kuskmen

**Comment by BrianNichols** [comment]
We don't have a formal code of conduct.  I do recommend using the same code format conventions as the existing code.  Pull requests are welcome, but try to avoid breaking the external public API.
