### ISSUE TITLE
There should be support for IDistributedCache

### ISSUE THREAD

**Issue by MovGP0** [aerospike/aerospike-client-csharp#37]
There should be support for the `IDistributedCache` interface, to allow to use Aerospike on the new .NET Standard/Core infrastructure, instead of Redis or SQL Server: 

* NuGet: [Microsoft.Extensions.Caching.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Abstractions/)
* Documentation: [Microsoft.Extensions.Caching.Distributed.IDistributedCache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache?view=aspnetcore-2.1)

**Comment by BrianNichols** [comment]
Aerospike currently supports the ASP.NET session state provider interface:

https://github.com/aerospike/aspnet-aerospike-providers

We will research IDistributedCache for possible integration.

**Comment by BrianNichols** [comment]
Aerospike.Extensions.Caching 1.0.0 has been released.

Github: https://github.com/aerospike/aerospike-net-extensions
Nuget:  https://www.nuget.org/packages/Aerospike.Extensions.Caching/1.0.0

Let us know how this works for you.
