### ISSUE TITLE
Potential enhancement: Query result interfaces for mocking frameworks to utilize

### ISSUE THREAD

**Issue by Jac21** [aerospike/aerospike-client-csharp#45]
I'm currently at a loss when it comes to unit testing some functionality within my applications that take advantage of query results. To be clear, I've mainly been working within Moq and related mocking frameworks, however, the inability to mock RecordSet instantiations have been a hurdle. I've read through a related issue concerning the Java client library, and this particular comment - https://github.com/aerospike/aerospike-client-java/issues/34#issuecomment-114685487

gives me hope that this may be up for consideration within the C# library. If there is some unspoken of way to overcome this, or if there may be a library update cooking for the near future that would provide this, please let me know, and thanks!

**Comment by BrianNichols** [comment]
The best way to resolve your issue is to create a pull request for the client library changes.  If the changes are reasonable and don't effect performance, we will incorporate them.

**Comment by Jac21** [comment]
Fantastic, raised a small PR over at #46 , let me know if there are any additional pieces or checks to add. Thank you.

**Comment by BrianNichols** [comment]
The pull request has been approved.
