### ISSUE TITLE
Negative int problem

### ISSUE THREAD

**Issue by hamednikzad** [aerospike/aerospike-client-csharp#51]
In versions 3.9.4 and 3.9.5 when inserting negative int values into set, real value inserted is unit.Max  (4294967295). while retreiving value client turns it back int same negative value but the actually inserted value is wrong. "this makes wrong indexing scan".
this code works correctly until version 3.9.3:

```
var bins = new Bin[] {new Bin("Test", -1)};
client.Add(policy, key, bins);
```

**Comment by BrianNichols** [comment]
That is a bug.  A new C# client has been released which restores the old integer behavior used in 3.9.3:

https://www.aerospike.com/download/client/csharp/3.9.6

**Comment by hamednikzad** [comment]
It's working! in new version (3.9.6). Thanks a lot
