### ISSUE TITLE
enum ListWriteFlags needs [Flags] attribute

### ISSUE THREAD

**Issue by jamejone** [aerospike/aerospike-client-csharp#53]
SonarQube is flagging a critical code smell:

![image](https://user-images.githubusercontent.com/7031519/84709563-6706a080-af30-11ea-800f-4474dd1d1710.png)

... because this enum:

https://github.com/aerospike/aerospike-client-csharp/blob/bd4ce5a69a82387b99268e84d14f0673c558cfbf/Framework/AerospikeClient/CDT/ListWriteFlags.cs#L22

... per [Microsoft's documentation](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute) should be decorated with a `[Flags]` attribute.

**Comment by BrianNichols** [comment]
The [Flags] attribute has been added to the following enums:

- ListWriteFlags
- MapWriteFlags
- BitResizeFlags
- BitWriteFlags
- HLLWriteFlags

This will appear in the next C# client release.

**Comment by BrianNichols** [comment]
C# client 3.9.7 is released: https://www.aerospike.com/download/client/csharp/notes.html#3.9.7
