### ISSUE TITLE
Replace BinaryFormatter  for .net 5

### ISSUE THREAD

**Issue by devIonutApostol** [aerospike/aerospike-client-csharp#55]
Hello, we migrated our app to .net 5 , but we had issues with the aerospike client because it uses BinaryFormatter which is disabled by default.
In order to enable it we used `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` in the csproj file. Do you plan to replace this in a future version ?

Best regards,
Ionut

**Comment by devIonutApostol** [comment]
Forgot to add a reference : https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2300?view=vs-2019

**Comment by BrianNichols** [comment]
It's not clear what you are suggesting.  BinaryFormatter is necessary for users who store complex C# objects on the server.  We can't remove BinaryFormatter support because some users still need to deserialize these stored objects.

Would adding a C# preprocessor directive to disable BinaryFormatter (the default would be enabled) suffice for your needs?

**Comment by devIonutApostol** [comment]
Updated the first comment. Would be more like a "nice to have" for us, but maybe there are contexts where this would be a critical issue.

**Comment by BrianNichols** [comment]
You are welcome to create a pull request to add EnableUnsafeBinaryFormatterSerialization to the csproj file.  Hopefully, it can be done in way that older versions of Visual Studio are still supported.

The question remains is if it's possible to support similar functionality with a different formatter, or just remove the functionality altogether.

**Comment by devIonutApostol** [comment]
I think that enabling EnableUnsafeBinaryFormatterSerialization is something that a developer should be aware by the consequences so adding this in the aerospike client project is not a way to go.  Maybe a warning in the documentation is enough.

I think the best way to replace BinaryFormatter is with protobuf https://github.com/protobuf-net/protobuf-net , but I'm not yet sure if it's backwards compatible

**Comment by BrianNichols** [comment]
Protobuf works fine on it's own, but it's not compatible with BinaryFormatter serialization.

**Comment by shannonklaus** [comment]
We removed BinaryFormatter in version 6.0.0

**Comment by shannonklaus** [comment]
We are recommending that everyone switch to using byte[] bins with other serialization formats. If you would still like to use BinaryFormatter you must use a different version of the client or create a custom build of the latest version that enables it.
https://developer.aerospike.com/client/csharp/incompatible
