### ISSUE TITLE
Option to call Tend and Asynctimeout in threadpool

### ISSUE THREAD

**Issue by devIonutApostol** [aerospike/aerospike-client-csharp#56]
The sdk creates 2 manual threads (tend and asynctimeout). I would prefer to move that logic to the threadpool, for example in some background tasks because in some cases even if we have a timeout of 300ms, I see that the asynctimeout thread gets CPU time every 3-4 seconds. Using cancellation tokens works ok, but still we want those actions on the threadpool.

Context: asp.net core, .net 5 rc1, high traffic (~12k IO per sec) 

Should I make a PR ?

**Comment by BrianNichols** [comment]
I need to understand what problem that the threadpool would solve.  How did you determine that the asynctimeout thread  gets cpu time once every 3-4 seconds when it should be sleeping for only 300ms?  Why does using the threadpool cause a thread to get more cpu time?

**Comment by devIonutApostol** [comment]
I will describe what happens. Usually happens 5-10 times a day , only for one random pod.
1. We get a lot of timeouts error from aerospike client and the circuit breaker kicks in (1 minute open) causing the aerospike requests to drop to 0 but seems that there are still outgoing requests.
2. After ~10 seconds other circuit breakers start to kick in. The healthcheck fails, we see some kubernetes cpu throttling .And some aerospike metrics like this
![aerospike issue](https://user-images.githubusercontent.com/66897281/94526343-121c3b00-023e-11eb-8a24-4f4b8dd6e756.png)
![connections_surge](https://user-images.githubusercontent.com/66897281/94526360-17798580-023e-11eb-9fdc-7aa6477ef56e.png)
3. After ~10-15 seconds, the system recovers ( aerospike circuit breaker is still open, but other CBs are not).

Healthchecks on aerospike server side doesn't found anything wrong, we have 3 nodes.

Async Client Configuration
`            AsyncClientPolicy aerospikePolicy = new AsyncClientPolicy
            {
                asyncMaxCommandAction = MaxCommandAction.REJECT,
                asyncMaxCommands = 1000,
                maxSocketIdle = 0,
                writePolicyDefault =
                {
                    commitLevel = CommitLevel.COMMIT_MASTER,
                    totalTimeout = 300,
                    maxRetries = 1
                },
                readPolicyDefault =
                {
                    totalTimeout = 300,
                    maxRetries = 1
                }
            };`

As regarding of moving those threads on the threadpool, is more actually a good practice. We just want some kind of option to call those tend and asynctimeout actions.

**Comment by devIonutApostol** [comment]
We modified the AsyncTimeoutQueue Run method to log the frequency of running

`private void Run()
		{
			var stopwatch = Stopwatch.StartNew();
			while (valid)
			{
				try
				{
					int t = (sleepInterval == int.MaxValue) ? Timeout.Infinite : sleepInterval + 1;

					if (cancelToken.WaitHandle.WaitOne(t))
					{
						// Cancel signal received.  Reset token under lock.
						lock (this)
						{
							cancel.Dispose();
							cancel = new CancellationTokenSource();
							cancelToken = cancel.Token;
						}
					}
					Console.WriteLine("AsyncTimeout run: " + " elapsed milliseconds since last run: " + stopwatch.ElapsedMilliseconds + " sleep interval: " + t);

					stopwatch.Restart();
					RegisterCommands();
					CheckTimeouts();
				}
				catch (Exception e)
				{
					if (valid && Log.WarnEnabled())
					{
						Log.Warn("AsyncTimeoutQueue error: " + e.Message);
					}
				}
			}
		}`

The result is something like this 

AsyncTimeout run:  elapsed milliseconds since last run: 0 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 198 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 54 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 85 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 54 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 300 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 300 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 45 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 44 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 45 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 45 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 45 sleep interval: -1
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 301 sleep interval: 301
AsyncTimeout run:  elapsed milliseconds since last run: 45 sleep interval: -1

**Comment by BrianNichols** [comment]
AsyncTimeoutQueue is performing as designed.  If there are no pending timer requests, the cancelToken wait is set to -1 (infinite). When a new timer request is added, the cancelToken is woken up and the next cancelToken wait is set to "timeout + 1".  The long sleeps occur because there are no timer requests during that time.

The threadpool alternative does not improve on the original design for AsyncTimeoutQueue or tend.  I prefer the control of deadicated threads over the shared thread support in threadpool.

**Comment by devIonutApostol** [comment]
Thanks for clarifications, after further investigations it seems that I was wrong about this.
