### ISSUE TITLE
Aerospike library Conflicts with Bcrypt

### ISSUE THREAD

**Issue by jlHertel** [aerospike/aerospike-client-csharp#60]
The Aerospike client library includes it's [own implementation][1] of the popular BCrypt algorithm.
This class unfortunately is not only outdated, but also using a very generic namespace, making it incompatible with anyone wanting to use a recent BCrypt nuget package like [BCrypt-Next][2].

Proposed solutions:
1. Change the namespace of the class (Sounds the most easier to me and with less issues)
2. Use a Nuget dependency for BCrypt, so we stay up-to-date with any security fix that comes out.

[1]: https://github.com/aerospike/aerospike-client-csharp/blob/master/Framework/AerospikeClient/BCrypt/BCrypt.cs
[2]: https://www.nuget.org/packages/BCrypt.Net-Next/

**Comment by BrianNichols** [comment]
We will change the namespace to "Aerospike.Client" in the next release.

**Comment by BrianNichols** [comment]
This change was implemented in C# client 4.1.6: https://download.aerospike.com/download/client/csharp/notes.html#4.1.6
