### ISSUE TITLE
TestSuite?

### ISSUE THREAD

**Issue by gregoryyoung** [aerospike/aerospike-client-csharp#7]
Is there some test suite associated with this that I am missing?

**Comment by BrianNichols** [comment]
No.  There is, however, AerospikeDemo which covers most client functionality.

**Comment by Caldas** [comment]
@BrianNichols do you inteend to create a test suite soon?

**Comment by BrianNichols** [comment]
A test suite is on the longer term roadmap.

**Comment by BrianNichols** [comment]
Version 3.1.4 has been released which contains a unit test suite.

**Comment by Caldas** [comment]
Why do you mixed a form application inside a test project?

**Comment by gregoryyoung** [comment]
@Caldas I agree that is a bit bizarre :)

**Comment by BrianNichols** [comment]
It's useful to be prompted for the password (for Enterprise version) and possibly other settings (hostname) before running the tests.

We can add the ability to bypass the form prompt in the next release.  In the meantime, just replace the following code in Suite.cs.

Old
<pre>
TestForm form = new TestForm();

if (form.ShowDialog() != DialogResult.OK)
{
	Application.Exit();
}
</pre>

New
<pre>
Args.Instance.Connect();
</pre>

**Comment by gregoryyoung** [comment]
I am guessing (don't mean to be offensive in any way) this is your first
time writing unit tests?

On Mon, Aug 3, 2015 at 7:54 PM, Brian Nichols <notifications@github.com>
wrote:

> It's useful to be prompted for the password (for Enterprise version) and
> possibly other settings (hostname) before running the tests.
>
> We can add the ability to bypass the form prompt in the next release. In
> the meantime, just replace the following code in Suite.cs.
>
> Old
>
> TestForm form = new TestForm();
>
> if (form.ShowDialog() != DialogResult.OK)
> {
>     Application.Exit();
> }
>
> New
>
> Args.Instance.Connect();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerospike/aerospike-client-csharp/issues/7#issuecomment-127349581>
> .
>



-- 
Studying for the Turing test

**Comment by BrianNichols** [comment]
Please explain.

**Comment by Caldas** [comment]
@BrianNichols I beleive @gregoryyoung was talking about the idea that unit test must have everything coded (or specified)

**Comment by gregoryyoung** [comment]
Yes @Caldas sorry @BrianNichols I missed your reply. I really didn't mean to be offensive at all. Seeing a "configuration UI" in unit tests

"It's useful to be prompted for the password (for Enterprise version) and possibly other settings (hostname) before running the tests.

We can add the ability to bypass the form prompt in the next release. In the meantime, just replace the following code in Suite.cs."

is highly suspect. This is not at all a common practice in people writing unit tests. As an example what would happen if this is running on my CI server? 

A more idiomatic approach might be to include say an embedded version of aerospike with the tests that is run to interact with (or something that maintains the same contracts). Another option would be to put this information into code/a config file etc. Prompting me when running unit tests is just not generally a good idea.

Sorry again for missing the previous response.

Greg

**Comment by manigandham** [comment]
I think there's some confusion here. It seems @gregoryyoung is looking for unit tests for the source code itself (correct?).

The Test project in this repo is for just testing the driver functionality itself and how it interacts with the database, not code level unit tests. Maybe it's the name that's confusing but it can just be thought of as a UI that lets you run the demo code (in the demo project).
