### ISSUE TITLE
Consider replacement for Iconic.Zlib.Netstandard

### ISSUE THREAD

**Issue by skolima** [aerospike/aerospike-client-csharp#90]
Package [Iconic.Zlib.Netstandard](https://www.nuget.org/packages/Iconic.Zlib.Netstandard) is outdated and unmaintained, targeted at long deprecated `.NETStandard 1.3`. This causes issues for consumers as it pulls in a lot of unexpected old packages.

Other implementations of Zlib available on NuGet aren't much better (but at least they have `netstandard-2.0` available) - but they aren't signed, which I understand is a requirement for Aerospike.Client?

Considering the only public type needed by [ByteUtil](https://github.com/aerospike/aerospike-client-csharp/blob/master/AerospikeClient/Command/ByteUtil.cs) is [ZlibStream](https://github.com/HelloKitty/Iconic.Zlib.Netstandard/blob/master/src/Iconic.Zlib.Netstandard/ZlibStream.cs), perhaps inlining this type (and it's dependencies) could be a reasonable approach?

**Comment by shannonklaus** [comment]
Thanks for bringing this to our attention. We are looking to replace Iconic.Zlib.Netstandard with [ZLibStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zlibstream?view=net-6.0) from [System.IO.Compression](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression?view=net-6.0) in a future release.

**Comment by shannonklaus** [comment]
We removed ZLibStream in release 7.0.0
